local codes = {
  'PEPPERSTHEBEST!',
  'DAVIDSTEBEST!',
  'YAMISTHEBEST!',
  '60KLIKES!',
  '40MVISITS!',
  'UPDATE5!',
  'SUB2Joltzy!',
  'SUB2D1SGUISED!',
  'SUB2CONSUME!',
  'SUB2WIRY!',
  'SUB2TOADBOI!',
  'SUB2RIJORO!',
  'SUB2VALK!',
  'SUB2ItsHappyYT1!',
  'FOLLOWEXVAR!'
}

return codes
