local codes = {
  'SORRYFORTHATBUGMYBAD!',
  '2KTWITTERFOLLOWS!',
  '20MVISITS!',
  'UPDATE3.5!',
  '15MVISITS!',
  '25KLIKES!',
  '30KLIKES!',
  '10MVISITS!',
  'UPDATE3!',
  'SORRYFORALLTHESHUTDOWNS',
  '20KLIKES!',
  'UPDATE2!',
  '5MVISITS!',
  '15KLIKES!',
  '10KLIKES!',
  '4KLIKES!',
  '5KLIKES!',
  '6KLIKES!',
  '500KVISITS!',
  '1MVISITS!',
  'SORRYFORSHUTDOWN!',
  '2KLIKES!',
  '1KLIKES!',
  'THANKS4PLAYING!',
  'RELEASE!'
}

return codes
