local ItemsRarities = {
    {"Special-Grade Sorcerer Jumpskirt", "Special Grade"},
    {"Prison Realm", "Legendary"},
    {"Curse Flesh", "Unobtainable"},
    {"Transfigured Human", "Rare"},
    {"Volcano Pants", "Legendary"},
    {"Heavenly Chains", "Rare"},
    {"Demon Blob", "Rare"},
    {"Beige Ronin Pants", "Rare"},
    {"Dorayaki", "Common"},
    {"Molten Ring", "Legendary"},
    {"Fighter Wrist Bands", "Special Grade"},
    {"Iron Blade", "Uncommon"},
    {"Title: Salmon Roe", "Unique"},
    {"Obsidian Pants", "Legendary"},
    {"Cursed Fragment", "Rare"},
    {"White Ronin Tunic", "Rare"},
    {"Zen Pants", "Uncommon"},
    {"Feathered Spear", "Special Grade"},
    {"Copper Ring", "Common"},
    {"Cursed Log", "Unobtainable"},
    {"Eyepatch", "Rare"},
    {"Bloody Black Cape", "Unique"},
    {"Black Suit", "Rare"},
    {"Fortune Gourd", "Legendary"},
    {"Perception Blocking Mask", "Legendary"},
    {"Special-Grade Sorcerer Jacket", "Special Grade"},
    {"Blessed Scarf", "Legendary"},
    {"Red Patterned Hoodie", "Legendary"},
    {"Dark Puffy Trousers", "Special Grade"},
    {"Title: Constructor", "Unique"},
    {"Gaze of Power", "Special Grade"},
    {"Black Tobi", "Rare"},
    {"Cloak of Inferno", "Special Grade"},
    {"Title: Champion", "Legendary"},
    {"Red Puff Jacket", "Special Grade"},
    {"Martial Fighter's Tobi", "Unique"},
    {"Magma Pants", "Legendary"},
    {"Black Ronin Tunic", "Rare"},
    {"Festive Hat", "Unobtainable"},
    {"Star Plasma Essence", "Unobtainable"},
    {"Iron Ring", "Uncommon"},
    {"Black Hakama", "Common"},
    {"Title: Cog", "Legendary"},
    {"Military Jeans", "Common"},
    {"Dark Heian Robe", "Unobtainable"},
    {"Dark Patterned Haori", "Legendary"},
    {"Garment of Balance", "Legendary"},
    {"Demonic Tobi", "Special Grade"},
    {"Awakened Prison Realm", "Special Grade"},
    {"Eyes of Bloodthirst", "Special Grade"},
    {"Grey Hakama", "Common"},
    {"Hazard Techsuit", "Legendary"},
    {"Blue Jeans", "Common"},
    {"Title: Voodooist", "Unique"},
    {"Garment of The Stars", "Legendary"},
    {"Sapphire Lotus", "Legendary"},
    {"Magma Shard", "Unobtainable"},
    {"Title: Heian Centimillionaire", "Unobtainable"},
    {"Purified Curse Hand", "Special Grade"},
    {"Energy Nature Scroll", "Special Grade"},
    {"Prison Realm Fragment", "Special Grade"},
    {"Night Grey Nagagi", "Common"},
    {"Blue Jade Wrist Beads", "Special Grade"},
    {"Obsidian Jacket", "Legendary"},
    {"Eerie Powder", "Unobtainable"},
    {"Ring of Thorns", "Special Grade"},
    {"Peach Shirt", "Common"},
    {"Rotten Ring", "Special Grade"},
    {"Tactful Ring", "Legendary"},
    {"Executioner Sword", "Common"},
    {"Orange Pants", "Common"},
    {"Paper Talisman", "Rare"},
    {"Sorcerer General's Top", "Special Grade"},
    {"Electric Staff", "Special Grade"},
    {"Jade Neck Beads", "Special Grade"},
    {"Iridescent Lotus", "Unique"},
    {"Investigate Essence", "Unobtainable"},
    {"Sapphire Pants", "Rare"},
    {"Ruin Shard", "Unobtainable"},
    {"Daylight Hakama", "Uncommon"},
    {"Jujutsu Society Executioner Top", "Unique"},
    {"Strongest Hat", "Unique"},
    {"Dark Hakama", "Common"},
    {"Capture Essence", "Unobtainable"},
    {"Peach Pants", "Common"},
    {"Blue Shirt", "Common"},
    {"Destroy Essence", "Unobtainable"},
    {"Teal Button Up Shirt", "Common"},
    {"Polished Beckoning Cat", "Legendary"},
    {"Title: Beyond Human", "Unique"},
    {"Dark Cotton Trousers", "Special Grade"},
    {"Black Beanie", "Common"},
    {"Gray Shirt", "Common"},
    {"Mastery Talisman", "Common"},
    {"Golem Totem", "Unobtainable"},
    {"High Ranking Sorcerer's Top", "Special Grade"},
    {"Damage Vial", "Common"},
    {"Title: Heian Demon", "Unobtainable"},
    {"Cryo Techsuit", "Rare"},
    {"Red Haori", "Rare"},
    {"Camo Tech Hoodie", "Legendary"},
    {"Title: Queen of Curses", "Unique"},
    {"Vengeance", "Special Grade"},
    {"Title: King of Fighters", "Legendary"},
    {"Scarf of The Chosen", "Unobtainable"},
    {"Golden Haori", "Unobtainable"},
    {"Silver Techsuit", "Uncommon"},
    {"Title: Lord of Domains", "Unobtainable"},
    {"Magma Jacket", "Legendary"},
    {"Takoyaki", "Common"},
    {"Purifying Dagger", "Uncommon"},
    {"Purple Pants", "Common"},
    {"Sorcerer General's Hakama", "Special Grade"},
    {"Ninja Headband", "Legendary"},
    {"Agility Vial", "Common"},
    {"Title: Heian Angel", "Unobtainable"},
    {"Rot Heart", "Unobtainable"},
    {"Domain Shard", "Unique"},
    {"Bandana", "Common"},
    {"Sorcerer Jumpskirt", "Uncommon"},
    {"Cursed Jacket", "Rare"},
    {"White High Skirt", "Common"},
    {"Soul Robe", "Special Grade"},
    {"Title: The Fraudulent One", "Unobtainable"},
    {"Mastery Scroll", "Rare"},
    {"Rust Techsuit", "Legendary"},
    {"Demonic Robe", "Special Grade"},
    {"Inverted Spear Of Heaven", "Legendary"},
    {"Title: please touch grass", "Unobtainable"},
    {"Blood Steel Ingot", "Unobtainable"},
    {"Title: The Exception", "Unique"},
    {"White Ronin Pants", "Rare"},
    {"Heian Era Pants", "Legendary"},
    {"Dark Heian Pants", "Unobtainable"},
    {"Dimensional Finger", "Unique"},
    {"Violet Ronin Tunic", "Rare"},
    {"Tokyo Subway Key", "Rare"},
    {"Deep Assassin Garment", "Legendary"},
    {"Zen Jacket", "Uncommon"},
    {"Bloodthirsty Hakama", "Legendary"},
    {"Demon Finger", "Legendary"},
    {"Frost Petal", "Common"},
    {"Jet Black", "Special Grade"},
    {"Beige Ronin Tunic", "Rare"},
    {"Cursebloom", "Common"},
    {"Title: The Abyss", "Unique"},
    {"White Tobi", "Rare"},
    {"Title: 7:3 Sorcerer", "Unique"},
    {"Heian Relic", "Unobtainable"},
    {"Expedition Scout Jacket", "Rare"},
    {"Soul Stitched Pants", "Legendary"},
    {"Cursed Tentacle", "Rare"},
    {"Long Puff Jacket", "Special Grade"},
    {"Waves Patterned Haori", "Legendary"},
    {"Midnight Hakama", "Uncommon"},
    {"Copy Katana", "Common"},
    {"Bloodthirsty Kimono", "Legendary"},
    {"Title: Restless Gambler", "Unique"},
    {"Black Shirt", "Common"},
    {"Soul Ring", "Legendary"},
    {"Rotten Chains", "Special Grade"},
    {"Ocean Blue Sailor's Vest", "Special Grade"},
    {"Black Ronin Pants", "Rare"},
    {"Blood Red Pants", "Rare"},
    {"Orange Haori", "Rare"},
    {"Sapphire Jacket", "Rare"},
    {"Cursed School Key", "Rare"},
    {"Title: Heart of Fire", "Unique"},
    {"Overflowing Ring", "Legendary"},
    {"Curse User Essence", "Unobtainable"},
    {"Bonsai Wood", "Unobtainable"},
    {"Volcanic Ash", "Rare"},
    {"Release Party Hat", "Unobtainable"},
    {"Title: Release Festival", "Unobtainable"},
    {"Title: lab rat", "Unique"},
    {"Title: Stand Proud", "Unobtainable"},
    {"Festive Top", "Unobtainable"},
    {"The Impossible Dream", "Special Grade"},
    {"Title: Divine Heian Sorcerer", "Unobtainable"},
    {"Title: Jujutsu CIA", "Unobtainable"},
    {"Title: Jujutsu IRS", "Unobtainable"},
    {"Title: Maximum Merchant", "Unobtainable"},
    {"Title: Unchained", "Unique"},
    {"Health Vial", "Common"},
    {"Lobotomy Volcano", "Unobtainable"},
    {"Title: Heian Era Sorcerer", "Unique"},
    {"Jujutsu Society Executioner Bottom", "Unique"},
    {"Title: Domain Master", "Unobtainable"},
    {"Title: Maximum Overdrive", "Unobtainable"},
    {"Withered Beckoning Cat", "Uncommon"},
    {"Overtime Suit", "Special Grade"},
    {"Title: God of Domains", "Unobtainable"},
    {"Lobotomy Volcano Cape", "Unique"},
    {"Title: Heian Multimillionaire", "Unobtainable"},
    {"Title: Heian Spirit", "Unobtainable"},
    {"Rusty Katana", "Common"},
    {"Title: go outside", "Unobtainable"},
    {"Title: El Finger", "Unobtainable"},
    {"Title: Ice Chef", "Unique"},
    {"Turbo Mask", "Unobtainable"},
    {"Special-Grade Sorcerer Pants", "Special Grade"},
    {"Heian Gauntlet", "Unobtainable"},
    {"Lord's Gaze", "Unique"},
    {"Martial Fighter's Haori", "Unique"},
    {"Spring Patterned Haori", "Legendary"},
    {"Snow White Nagagi", "Rare"},
    {"Blood Stained Neck Beads", "Unique"},
    {"Blood Stained Beads", "Unique"},
    {"Title: Heian Millionaire", "Unobtainable"},
    {"Eyes of Willpower", "Special Grade"},
    {"Title: Martial Demon", "Rare"},
    {"Title: Warlord", "Common"},
    {"Title: Battle Crazy", "Common"},
    {"Title: Brawler", "Common"},
    {"High Ranking Sorcerer's Hakama", "Special Grade"},
    {"Eyes of Insight", "Special Grade"},
    {"Viscera Scythe", "Special Grade"},
    {"Spring Puff", "Common"},
    {"Title: Battleworn", "Common"},
    {"Title: The Ultimate Being", "Unique"},
    {"Soul Face Stitches", "Legendary"},
    {"Red Shirt", "Common"},
    {"Hard Boiled Prisoner Shirt", "Legendary"},
    {"Title: Killer", "Common"},
    {"Title: Fighter", "Common"},
    {"Title: Shadow Ninja", "Unique"},
    {"Title: The Witch", "Unique"},
    {"Wooden Beckoning Cat", "Rare"},
    {"Title: Finger Collector", "Unobtainable"},
    {"Title: Blood Reaper", "Unique"},
    {"Rot Cleanser", "Legendary"},
    {"Mission Essence", "Rare"},
    {"Title: Judicial Prodigy", "Unique"},
    {"Blood Sword", "Special Grade"},
    {"Split Soul", "Special Grade"},
    {"Rage Gourd", "Rare"},
    {"Cursed Alloy Ingot", "Unobtainable"},
    {"Violet Patterned Haori", "Special Grade"},
    {"Title: Volcano Head", "Unique"},
    {"Dimensional Maximum Scroll", "Unique"},
    {"Violet Tobi", "Rare"},
    {"Title: The Singularity", "Unique"},
    {"Eerie Metal Ingot", "Unobtainable"},
    {"Cracked Stone", "Unobtainable"},
    {"Heian Era Robe", "Legendary"},
    {"Enlightenment Beads", "Unobtainable"},
    {"Sleeveless Puff Jacket", "Special Grade"},
    {"Slaughter Demon", "Rare"},
    {"Heavenly Black Shirt", "Legendary"},
    {"Black Button Up Shirt", "Common"},
    {"Title: The Strongest", "Unique"},
    {"Title: Warrior", "Rare"},
    {"Cargo Pants", "Common"},
    {"Festive Pants", "Unobtainable"},
    {"Yasohachi Bridge Key", "Rare"},
    {"Silver Ring", "Rare"},
    {"Focus Vial", "Common"},
    {"White Lotus", "Rare"},
    {"White Button Up Shirt", "Common"},
    {"Copy", "Common"},
    {"Brown Shirt", "Common"},
    {"Green Haori", "Rare"},
    {"Rage Filled Chains", "Special Grade"},
    {"Orange Shirt", "Common"},
    {"Maximum Scroll", "Unique"},
    {"Luck Vial", "Common"},
    {"Gaze of Rage", "Special Grade"},
    {"Sorcerer Jacket", "Uncommon"},
    {"Resonating Eyepatch", "Legendary"},
    {"Crimson Patterned Haori", "Legendary"},
    {"Inventory Curse", "Unique"},
    {"Jade Wrist Beads", "Special Grade"},
    {"Golden Beckoning Cat", "Special Grade"},
    {"Eerie Farm Key", "Rare"},
    {"Title: Maximum Master", "Unobtainable"},
    {"Baseball Cap", "Rare"},
    {"Blue Jade Neck Beads", "Special Grade"},
    {"A Sinner's Suit", "Legendary"},
    {"Demon Face", "Legendary"},
    {"Wise Man's Kimono", "Legendary"},
    {"Exorcise Essence", "Unobtainable"},
    {"A Sinner's Cloak", "Legendary"},
    {"Focus Gourd", "Uncommon"},
    {"Black Techsuit", "Uncommon"},
    {"Title: Nah I'd Win", "Unobtainable"},
    {"Puffy Shorts", "Special Grade"},
    {"A Sinner's Trousers", "Legendary"},
    {"Blood Red Jacket", "Rare"},
    {"Ocean Jacket", "Legendary"},
    {"Grey High Skirt", "Common"},
    {"Sorcerer Pants", "Uncommon"},
    {"Onyx Techsuit", "Rare"},
    {"Overtime Trousers", "Special Grade"},
    {"Brown Haori", "Common"},
    {"Vest Of Ruin", "Legendary"},
    {"Deep Black Sailor's Vest", "Special Grade"},
    {"Title: King of Curses", "Unique"},
    {"Strongest Bottom Half", "Unobtainable"},
    {"Beige Tobi", "Rare"},
    {"Effigy Nail", "Unobtainable"},
    {"Detention Center Key", "Rare"},
    {"Black Pants", "Rare"},
    {"Hard Boiled Prisoner Pants", "Legendary"},
    {"Damage Gourd", "Uncommon"},
    {"Dragon Bone", "Special Grade"},
    {"Headphones", "Legendary"},
    {"Wise Man's Hakama", "Legendary"},
    {"Dusk Hakama", "Legendary"},
    {"Ravenous Axe", "Special Grade"},
    {"Title: Snow Angel", "Unobtainable"},
    {"Midnight Button Up Shirt", "Common"},
    {"Powerful Ring", "Legendary"},
    {"Sakura Hakama", "Rare"},
    {"Jade Lotus", "Special Grade"},
    {"Sorcerer Killer Pants", "Legendary"},
    {"Red High Skirt", "Common"},
    {"Playful Cloud", "Special Grade"},
}

return ItemsRarities;
