local Cards = {
    "Weakened Resolve I", "Weakened Resolve II", "Weakened Resolve III",
    "Fog of War I", "Fog of War II", "Fog of War III",
    "Lingering Fear I", "Lingering Fear II",
    "Power Reversal I", "Power Reversal II",
    "Greedy Vampire's", "Hellish Gravity", "Deadly Striker",
    "Critical Denial", "Trick or Treat Coin Flip",
    "Devil's Sacrifice",
    "Bullet Breaker I", "Bullet Breaker II", "Bullet Breaker III",
    "Hell Merchant I", "Hell Merchant II", "Hell Merchant III",
    "Hellish Warp I", "Hellish Warp II",
    "Fiery Surge I", "Fiery Surge II",
    "Grevious Wounds I", "Grevious Wounds II",
    "Scorching Hell I", "Scorching Hell II",
    "Fortune Flow", "Soul Link", "Seething Bloodlust"
}

return Cards;
